ACTION_IF (RESOURCE_CONTAINS ~UI.MENU~ ~rgGetGameEnginePortraits~) BEGIN
  ACTION_IF NOT (RESOURCE_CONTAINS ~UI.MENU~ ~2MPAL1_~) BEGIN
    FAIL @1002
  END
  COPY_EXISTING ~UI.MENU~ ~override~
    REPLACE_TEXTUALLY ~{'2MPAL1_', 1},~ ~{'2MPAL1_', 1},
        {'x!eff_', 2},
        {'x!hffb_', 2},
        {'x!2mb1_', 1},
        {'x!2mb1b', 1},
        {'x!hefcb', 2},
        {'x!hefcc', 2},
        {'x!hefcd', 2},
        {'x!hmc2_', 1},
        {'x!hfw3b', 2},
        {'x!gmtb_', 1},~
  BUT_ONLY
END ELSE BEGIN
  COPY ~IWDEE-Ineth-Portraits/data/m_iip_photoshopped.lua~ ~override/m_iip_photoshopped.lua~
END
